openapi: 3.0.1
info:
  title: Menu API
  description: Menu API for interacting with the Menu service
  version: 1.0.0
servers:
  - url: 'https://localhost:8091'

tags:
  - name: MenuItem
  - name: MenuCategory
  - name: Ingredient

paths:
  /v1/menu-items:
    $ref: 'paths/menu.yaml#/menuItems'
  /v1/menu-items/{id}:
    $ref: 'paths/menu.yaml#/menuItemById'
  /v1/menu-categories/{categoryId}/menu-items:
    $ref: 'paths/menu.yaml#/menuItemsByCategory'
  /v1/menu-items/{menuItemId}/ingredients:
    $ref: 'paths/menu.yaml#/menuItemWithIngredients'
  /v1/menu-items/{menuItemId}/ingredients/{ingredientId}:
    $ref: 'paths/menu.yaml#/menuItemIngredient'
  /v1/menu-info:
    $ref: 'paths/menu.yaml#/menuInfo'

  /v1/menu-categories:
    $ref: 'paths/category.yaml#/menuCategories'
  /v1/menu-categories/{id}:
    $ref: 'paths/category.yaml#/menuCategoryById'

  /v1/ingredients:
    $ref: 'paths/ingredient.yaml#/ingredients'
  /v1/ingredients/{id}:
    $ref: 'paths/ingredient.yaml#/ingredientById'

components:
  schemas:
    MenuItemResponse:
      $ref: '#/components/schemas/MenuItemResponse'
    MenuItemPageResponse:
      $ref: '#/components/schemas/MenuItemPageResponse'
    CreateMenuItemRequest:
      $ref: '#/components/schemas/CreateMenuItemRequest'
    UpdateMenuRequest:
      $ref: '#/components/schemas/UpdateMenuRequest'
    SortBy:
      $ref: '#/components/schemas/SortBy'

    MenuCategoryResponse:
      $ref: '#/components/schemas/MenuCategoryResponse'
    MenuCategoryPageResponse:
      $ref: '#/components/schemas/MenuCategoryPageResponse'
    CreateMenuCategoryRequest:
      $ref: '#/components/schemas/CreateMenuCategoryRequest'
    UpdateMenuCategoryRequest:
      $ref: '#/components/schemas/UpdateMenuCategoryRequest'

    IngredientResponse:
      $ref: '#/components/schemas/IngredientResponse'
    IngredientPageResponse:
      $ref: '#/components/schemas/IngredientPageResponse'
    CreateIngredientRequest:
      $ref: '#/components/schemas/CreateIngredientRequest'
    UpdateIngredientRequest:
      $ref: '#/components/schemas/UpdateIngredientRequest'

    ErrorResponse:
      $ref: '#/components/schemas/ErrorResponse'

  responses:
    BadRequest:
      $ref: '#/components/responses/BadRequest'
    Unauthorized:
      $ref: '#/components/responses/Unauthorized'
    Forbidden:
      $ref: '#/components/responses/Forbidden'
    NotFound:
      $ref: '#/components/responses/NotFound'
    Conflict:
      $ref: '#/components/responses/Conflict'
    NoContent:
      $ref: '#/components/responses/NoContent'

  parameters:
    IdPathParam:
      $ref: '#/components/parameters/IdPathParam'
    CategoryIdPathParam:
      $ref: '#/components/parameters/CategoryIdPathParam'
    CategoryIdFilterParam:
      $ref: '#/components/parameters/CategoryIdFilterParam'
    ActiveFilterParam:
      $ref: '#/components/parameters/ActiveFilterParam'
    NameFilterParam:
      $ref: '#/components/parameters/NameFilterParam'
    PageParam:
      $ref: '#/components/parameters/PageParam'
    SizeParam:
      $ref: '#/components/parameters/SizeParam'
    SortByParam:
      $ref: '#/components/parameters/SortByParam'