services:
  menu-service:
    #image: menu-service # в сервисе запустить gradle bootBuildImage
    build:
      context: ./menu-service
    container_name: "menu-service"
    depends_on:
      menu-postgres:
        condition: service_healthy
      cloud-config:
        condition: service_healthy
    ports:
      - "8091:8091"
    networks: [ backend, menu-db ]
    environment:
      POSTGRES_HOST: menu-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: menu-user
      POSTGRES_PASSWORD: menu1234
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8091/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 30

  menu-postgres:
    image: postgres:17
    container_name: menu-postgres
    networks: [ menu-db ]
    environment:
      POSTGRES_USER: menu-user
      POSTGRES_PASSWORD: menu1234
      POSTGRES_DB: menu
    volumes:
      - ./infrastructure/databases/menu:/docker-entrypoint-initdb.d:ro
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U menu-user -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20

  order-service:
    # image: orders-service # в сервисе запустить gradle bootBuildImage
    build:
      context: ./orders-service
    container_name: "orders-service"
    depends_on:
      order-postgres:
        condition: service_healthy
      cloud-config:
        condition: service_healthy
    networks: [ backend, order-db ]
    ports:
      - "8092:8092"
    environment:
      POSTGRES_HOST: order-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: order-user
      POSTGRES_PASSWORD: order1234
      MENU_SERVICE_URL: http://menu-service:8091
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8092/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 30

  order-postgres:
    image: postgres:17
    container_name: order-postgres
    networks: [ order-db ]
    environment:
      POSTGRES_USER: order-user
      POSTGRES_PASSWORD: order1234
      POSTGRES_DB: orders
    volumes:
      - ./infrastructure/databases/order:/docker-entrypoint-initdb.d:ro
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U order-user -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20

  reviews-service:
    #image: reviews-service # в сервисе запустить gradle bootBuildImage
    build:
      context: ./reviews-service
    container_name: "reviews-service"
    depends_on:
      review-postgres:
        condition: service_healthy
      cloud-config:
        condition: service_healthy
    networks: [ backend, review-db ]
    ports:
      - "8093:8093"
    environment:
      POSTGRES_HOST: review-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: review-user
      POSTGRES_PASSWORD: review1234
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8093/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 30

  review-postgres:
    image: postgres:17
    container_name: review-postgres
    environment:
      POSTGRES_USER: review-user
      POSTGRES_PASSWORD: review1234
      POSTGRES_DB: review
    networks: [ review-db ]
    volumes:
      - ./infrastructure/databases/review:/docker-entrypoint-initdb.d:ro
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U review-user -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20

  menu-aggregate-service:
    #image: menu-aggregate-service # в сервисе запустить gradle bootBuildImage
    build:
      context: ./menu-aggregate-service
    container_name: "menu-aggregate-service"
    depends_on:
      cloud-config:
        condition: service_healthy
    ports:
      - "8094:8094"
    networks: [ backend ]
    environment:
      MENU_SERVICE_URL: http://menu-service:8091
      REVIEW_SERVICE_URL: http://reviews-service:8093
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8094/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 30

  cloud-config:
    #image: cloud-config # в сервисе запустить gradle bootBuildImage
    build:
      context: ./cloud-config
    container_name: "cloud-config"
    ports:
      - "8090:8090"
    networks: [ backend ]
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 30

networks:
  backend:
  menu-db:
  order-db:
  review-db:
