services:
  menu-service:
    image: menu-service # в сервисе запустить gradle bootBuildImage
    container_name: "menu-service"
    depends_on:
      menu-postgres:
        condition: service_healthy
    ports:
      - "8091:8091"
    environment:
      POSTGRES_HOST: menu-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: menu-user
      POSTGRES_PASSWORD: menu1234
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      interval: 5s
      timeout: 5s
      retries: 30

  menu-postgres:
    image: postgres:17
    container_name: menu-postgres
    environment:
      POSTGRES_USER: menu-user
      POSTGRES_PASSWORD: menu1234
      POSTGRES_DB: menu
    volumes:
      - ./infrastructure/databases/menu:/docker-entrypoint-initdb.d:ro
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U menu-user -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20

  order-service:
    image: orders-service # в сервисе запустить gradle bootBuildImage
    container_name: "orders-service"
    depends_on:
      order-postgres:
        condition: service_healthy
    ports:
      - "8092:8092"
    environment:
      POSTGRES_HOST: order-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: order-user
      POSTGRES_PASSWORD: order1234
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      interval: 5s
      timeout: 5s
      retries: 30

  order-postgres:
    image: postgres:17
    container_name: order-postgres
    environment:
      POSTGRES_USER: order-user
      POSTGRES_PASSWORD: order1234
      POSTGRES_DB: orders
    volumes:
      - ./infrastructure/databases/order:/docker-entrypoint-initdb.d:ro
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U order-user -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20

  reviews-service:
    image: reviews-service # в сервисе запустить gradle bootBuildImage
    container_name: "reviews-service"
    depends_on:
      review-postgres:
        condition: service_healthy
    ports:
      - "8093:8093"
    environment:
      POSTGRES_HOST: review-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: review-user
      POSTGRES_PASSWORD: review1234
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      interval: 5s
      timeout: 5s
      retries: 30

  review-postgres:
    image: postgres:17
    container_name: review-postgres
    environment:
      POSTGRES_USER: review-user
      POSTGRES_PASSWORD: review1234
      POSTGRES_DB: review
    volumes:
      - ./infrastructure/databases/review:/docker-entrypoint-initdb.d:ro
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U review-user -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20