services:
  menu-service:
    #image: menu-service # в сервисе запустить gradle bootBuildImage
    build:
      context: ./menu-service
    container_name: "menu-service"
    depends_on:
      menu-postgres:
        condition: service_healthy
      cloud-config:
        condition: service_healthy
    ports:
      - "8091:8091"
    networks: [ backend, menu-db ]
    environment:
      POSTGRES_HOST: menu-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: menu-user
      POSTGRES_PASSWORD: menu1234
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8091/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 30

  menu-postgres:
    image: postgres:17
    container_name: menu-postgres
    networks: [ menu-db ]
    environment:
      POSTGRES_USER: menu-user
      POSTGRES_PASSWORD: menu1234
      POSTGRES_DB: menu
    volumes:
      - ./infrastructure/databases/menu:/docker-entrypoint-initdb.d:ro
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U menu-user -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20

  order-service:
    # image: orders-service # в сервисе запустить gradle bootBuildImage
    build:
      context: ./orders-service
    container_name: "orders-service"
    depends_on:
      order-postgres:
        condition: service_healthy
      cloud-config:
        condition: service_healthy
    networks: [ backend, order-db ]
    ports:
      - "8092:8092"
    environment:
      POSTGRES_HOST: order-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: order-user
      POSTGRES_PASSWORD: order1234
      MENU_SERVICE_URL: http://menu-service:8091
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8092/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 30

  order-postgres:
    image: postgres:17
    container_name: order-postgres
    networks: [ order-db ]
    environment:
      POSTGRES_USER: order-user
      POSTGRES_PASSWORD: order1234
      POSTGRES_DB: orders
    command: [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - ./infrastructure/databases/order:/docker-entrypoint-initdb.d:ro
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U order-user -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20

  reviews-service:
    #image: reviews-service # в сервисе запустить gradle bootBuildImage
    build:
      context: ./reviews-service
    container_name: "reviews-service"
    depends_on:
      review-postgres:
        condition: service_healthy
      cloud-config:
        condition: service_healthy
    networks: [ backend, review-db ]
    ports:
      - "8093:8093"
    environment:
      POSTGRES_HOST: review-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: review-user
      POSTGRES_PASSWORD: review1234
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8093/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 30

  review-postgres:
    image: postgres:17
    container_name: review-postgres
    environment:
      POSTGRES_USER: review-user
      POSTGRES_PASSWORD: review1234
      POSTGRES_DB: review
    networks: [ review-db ]
    volumes:
      - ./infrastructure/databases/review:/docker-entrypoint-initdb.d:ro
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U review-user -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20

  menu-aggregate-service:
    #image: menu-aggregate-service # в сервисе запустить gradle bootBuildImage
    build:
      context: ./menu-aggregate-service
    container_name: "menu-aggregate-service"
    depends_on:
      cloud-config:
        condition: service_healthy
    ports:
      - "8094:8094"
    networks: [ backend ]
    environment:
      MENU_SERVICE_URL: http://menu-service:8091
      REVIEW_SERVICE_URL: http://reviews-service:8093
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8094/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 30

  cloud-config:
    #image: cloud-config # в сервисе запустить gradle bootBuildImage
    build:
      context: ./cloud-config
    container_name: "cloud-config"
    ports:
      - "8090:8090"
    networks: [ backend ]
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 30

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller

      # PLAINTEXT (29092) — для общения между брокерами внутри docker-сети
      # CONTROLLER (9093) — служебный, для кворума KRaft, клиенты сюда не ходят
      # PLAINTEXT_HOST (9092) — для подключения с хоста (например, с локальной машины)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - backend
    healthcheck:
      test: [
        "CMD-SHELL",
        "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:29092 --list"
      ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - backend
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-connect:
    build:
      context: ./infrastructure/debezium
    container_name: kafka-connect
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_started
      order-postgres:
        condition: service_healthy
    ports:
      - "8083:8083"
    networks:
      - backend
      - order-db
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: connect-cluster
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081


volumes:
  kafka_data:

networks:
  backend:
  menu-db:
  order-db:
  review-db:
