server:
  port: 8092
  shutdown: graceful
  netty:
    connection-timeout: 3s
    idle-timeout: 20s

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:openapi-descriptions.yaml
  application:
    name: orders-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  r2dbc:
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5435}/orders
    pool:
      max-create-connection-time: 2s
      initial-size: 6
      max-size: 12

  flyway:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/orders
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: classpath:db/migration

external:
  menu-service-url: "${MENU_SERVICE_URL:http://localhost:8091}"
  menu-info-path: "/v1/menu-info"
  default-timeout: 2s
  retry-backoff: 100ms
  retry-count: 5
  # фактор неопределенности для того, чтобы минимизировать возможность сценария,
  # при котором несколько инстансов Orders Service будут одновременно посылать ретраи в Menu Service.
  retry-jitter: 0.75

logging:
  config: "classpath:logback.xml"