spring:
  application:
    name: menu-aggregate-service
  config:
    import:
      - optional:file:.env[.properties]
      - configserver:http://${CONFIG_SERVER_URL:localhost}:8090

  cloud:
    config:
      label: master