springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  get-aggregate:
    summary: Получение подробной информации о блюде по его идентификатору.
    description: |
      Предоставляет информацию о блюде, пользовательских отзывах к нему, а также рейтинге блюда.
      В случае невозможности получить информацию о рейтинге и отзывах пользователя предоставляется
      частичный ответ с указанием на ошибку загрузки данных. 
      Список отзывов отсортирован и пагинирован согласно параметрам запроса. 
      Варианты сортировки:
      - date_asc - по дате создания от старых к новым
      - date_desc - по дате создания от новых к старым
  get-aggregate-list:
    summary: Получение списка блюд и их рейтингов из конкретной категории.
    description: |
      Предоставляет список блюд, содержащий дополнительную информацию о каждом блюде:
      - рейтинг
      - средняя оценка
      Список отсортирован согласно параметрам запроса.
      Варианты сортировки: 
      - az / za - по алфафиту
      - date_asc / date_desc - по дате создания
      - price_asc / price_desc - по цене
      - rate_asc / rate_desc - по рейтингу
  response:
    getAggregateOk: Информация о блюде успешно сформирована.
    getAggregateListOk: Список блюд успешно сформирован.
    notFound: Блюдо по указанному идентификатору не найдено.
    badRequest: Ответ не был сформирован из-за ошибки во входящих параметрах. Подробнее в сообщении об ошибке.
    serviceUnavailable: Ответ не был сформирован из-за недоступности одной из внешних систем. Подробнее в сообщении об ошибке.